/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "super_admin" | "user";

export interface AnchorEmbedding {
  anchor_id: string;
  embedding: number[] | null;
  embedding_version: string | null;
  generation: string;
  image_sha256: string | null;
  image_url: string;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface AnchorMatchRateLimit {
  request_count: number;
  window_start: Timestamp;
  workspace_id: string;
}

export interface AppConfig {
  key: string;
  updated_at: Generated<Timestamp>;
  value: Json;
}

export interface Asset {
  anchor_id: string | null;
  config: Generated<Json>;
  content_hash: string | null;
  create_at: Generated<Timestamp | null>;
  created_by: string | null;
  file_type: string;
  file_url: string | null;
  id: Generated<string>;
  is_huge: Generated<boolean>;
  location: string | null;
  metadata: Generated<Json | null>;
  name: string | null;
  tag_ids: Generated<string[] | null>;
  text_content: string | null;
  updated_at: Generated<Timestamp>;
  workspace_id: Generated<string[] | null>;
}

export interface AuthAccount {
  access_token: string | null;
  access_token_expires_at: Timestamp | null;
  account_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Timestamp | null;
  scope: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthSession {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_agent: string | null;
  user_id: string;
}

export interface AuthUsers {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified: Generated<boolean>;
  id: Generated<string>;
  image: string | null;
  name: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AuthVerification {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  identifier: string;
  updated_at: Generated<Timestamp>;
  value: string;
}

export interface ErrorLog {
  context: Json | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  message: string | null;
  method: string | null;
  path: string | null;
  scope: string | null;
  status: number | null;
  user_id: string | null;
}

export interface GeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface Organization {
  allowed_file_types: string[] | null;
  config: Generated<Json>;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  description: string | null;
  id: Generated<string>;
  map_center: Json | null;
  name: string;
}

export interface OrganizationInvitation {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  expires_at: Timestamp | null;
  id: Generated<string>;
  organization_id: string;
  revoked: Generated<boolean>;
  role: Generated<string>;
  token: string;
  use_count: Generated<number>;
  workspace_id: string | null;
}

export interface OrganizationMember {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  organization_id: string;
  role: Generated<string>;
  user_id: string;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  name: string;
}

export interface Tag {
  color: Generated<string | null>;
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  workspace_id: string;
}

export interface UserOrganizationPin {
  organization_id: string;
  pinned_at: Generated<Timestamp>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  email: string | null;
  last_sign_in_at: Timestamp | null;
  name: string | null;
  role: Generated<UserRole>;
  user_id: string;
}

export interface Workspace {
  create_date: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<string>;
  name: string;
  organization_id: string;
}

export interface WorkspaceAssignment {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: Generated<string>;
  user_id: string;
  workspace_id: string;
}

export interface DB {
  anchor_embedding: AnchorEmbedding;
  anchor_match_rate_limit: AnchorMatchRateLimit;
  app_config: AppConfig;
  asset: Asset;
  "auth.account": AuthAccount;
  "auth.session": AuthSession;
  "auth.users": AuthUsers;
  "auth.verification": AuthVerification;
  error_log: ErrorLog;
  geography_columns: GeographyColumns;
  geometry_columns: GeometryColumns;
  organization: Organization;
  organization_invitation: OrganizationInvitation;
  organization_member: OrganizationMember;
  schema_migrations: SchemaMigrations;
  tag: Tag;
  user_organization_pin: UserOrganizationPin;
  users: Users;
  workspace: Workspace;
  workspace_assignment: WorkspaceAssignment;
}
